### ISSUE TITLE
KeyError "expressions"

### ISSUE THREAD

**Issue by Deadervant** [pladisdev/VTS-AI-Plugin#2]
I have not modified the code at all, and I am receiving this KeyError every time I try to run it. Is there something I am doing wrong? I'm new to VTube Studio and its API.

![vts py - Visual Studio Code 7_25_2023 5_02_38 PM](https://github.com/pladisdev/VTS-AI-Plugin/assets/140558250/0adf5275-a571-4e52-83a5-ff0a83b7d071)

**Comment by pladisdev** [comment]
I pushed an update with some more error checking. But I think the issue was I accidently uploaded my VTS token...

If there are any more problems let me know.
